### Tag CRUD API 테스트
@baseUrl = http://localhost:8080

# Todo 생성
# 먼저 member/signin.http 에서 로그인하여 JWT 토큰을 받기


### Tag 생성 - 성공
POST {{baseUrl}}/api/v1/tags
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "개발",
  "color": "#FF5733"
}


### Tag 생성 - 프론트엔드
POST {{baseUrl}}/api/v1/tags
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "프론트엔드",
  "color": "#3498DB"
}


### Tag 생성 - 백엔드
POST {{baseUrl}}/api/v1/tags
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "백엔드",
  "color": "#2ECC71"
}


### Tag 생성 - 중복 이름 (실패)
POST {{baseUrl}}/api/v1/tags
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "개발",
  "color": "#FF5733"
}


### Tag 전체 조회
GET {{baseUrl}}/api/v1/tags
Authorization: Bearer {{authToken}}


### Tag 단건 조회
GET {{baseUrl}}/api/v1/tags/1
Authorization: Bearer {{authToken}}


### Tag 단건 조회 - 존재하지 않는 ID (실패)
GET {{baseUrl}}/api/v1/tags/999
Authorization: Bearer {{authToken}}


### Tag 삭제
DELETE {{baseUrl}}/api/v1/tags/1
Authorization: Bearer {{authToken}}
